# Generated by Django 5.0.6 on 2024-06-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='students',
            name='country',
            field=models.CharField(default='', max_length=100, verbose_name='Pais de nacimiento'),
        ),
        migrations.AddField(
            model_name='students',
            name='state',
            field=models.CharField(default='', max_length=100, verbose_name='Departamento'),
        ),
    ]
