# Generated by Django 5.0.6 on 2024-06-04 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_city_students_country_students_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(max_length=8, verbose_name='Telefono'),
        ),
    ]
