# Generated by Django 5.0.6 on 2024-06-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_students_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.IntegerField(max_length=8, verbose_name='Telefono'),
        ),
    ]
