# Generated by Django 5.0.6 on 2024-07-21 23:22

import students.validators.validate_phone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_students_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.IntegerField(validators=[students.validators.validate_phone.validate_phone], verbose_name='Telefono'),
        ),
    ]
