# Generated by Django 5.0.6 on 2024-06-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_system_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(max_length=150, unique=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name_spanish',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Nombre Español'),
        ),
    ]
