# Generated by Django 5.0.6 on 2024-07-21 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_system_authentication', '0002_alter_role_description_alter_role_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
    ]
