# Generated by Django 5.0.6 on 2024-07-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_system_authentication', '0004_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone_number',
            field=models.CharField(default='', max_length=25, verbose_name='Número de teléfono'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='private_key',
            field=models.CharField(default='', max_length=100, verbose_name='Clave privada'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='public_key',
            field=models.CharField(default='', max_length=100, verbose_name='Clave pública'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='token_email_validation',
            field=models.CharField(default='', max_length=100, verbose_name='Token para validar correo'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='token_expiration',
            field=models.DateTimeField(null=True, verbose_name='Fecha valida para token'),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='token_password_reset',
            field=models.CharField(default='', max_length=100, verbose_name='Token para reiniciar contraseña'),
        ),
    ]
