# Generated by Django 5.0.6 on 2024-07-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_system_authentication', '0005_useraccount_phone_number_useraccount_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='private_key',
            field=models.TextField(default='', verbose_name='Clave privada'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='public_key',
            field=models.TextField(default='', verbose_name='Clave pública'),
        ),
    ]
