# Generated by Django 5.0.6 on 2024-07-30 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_system_authentication', '0006_alter_useraccount_private_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='token_email_validation',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='token_expiration',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='token_password_reset',
        ),
    ]
