# Generated by Django 5.0.6 on 2024-08-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_system_authentication', '0007_remove_useraccount_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='accepted_terms',
            field=models.BooleanField(default=False, verbose_name='Aceptó los términos y condiciones'),
        ),
    ]
