# Generated by Django 5.0.6 on 2024-06-01 23:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proffesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, verbose_name='Telefono')),
                ('age', models.PositiveSmallIntegerField(verbose_name='Edad')),
                ('address', models.CharField(max_length=100, verbose_name='Direccion')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Genero')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de creacion')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['name'],
            },
        ),
    ]
