# Generated by Django 5.0.6 on 2024-06-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proffesor',
            name='phone',
            field=models.CharField(max_length=8, verbose_name='Telefono'),
        ),
    ]
