# Generated by Django 5.0.6 on 2024-08-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Course Code')),
                ('name', models.CharField(max_length=100, verbose_name='Course Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('credits', models.PositiveIntegerField(verbose_name='Credits')),
                ('modality', models.CharField(choices=[('online', 'Online'), ('in_person', 'In-Person'), ('hybrid', 'Hybrid')], max_length=20, verbose_name='Modality')),
                ('max_students', models.PositiveIntegerField(verbose_name='Maximum Students')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
